import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geomItalic = localFont({
  src: "./fonts/Geom-Italic-VariableFont_wght.ttf",
  variable: "--font-geom-italic",
  weight: "100 900",
});
const geomVariable = localFont({
  src: "./fonts/Geom-VariableFont_wght.ttf",
  variable: "--font-geom-variable",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "LushDecor Gyn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geomItalic.variable} ${geomVariable.variable} antialiased`}
        style={{overflowX: "hidden"}}
      >
        {children}
      </body>
    </html>
  );
}
